import "./_dnt.test_polyfills.js";
import { deepStrictEqual, rejects, strictEqual, throws } from "node:assert/strict";
import { test } from "node:test";
import { join } from "node:path";
import { pathToFileURL } from "node:url";
import { isWindows, withTestRoot, withTestRootSync } from "./_test_helpers.js";
import { readFile, readFileSync } from "./read_file.js";
import { exists } from "./exists.js";
import { stat, statSync } from "./stat.js";
import { writeFile, writeFileSync } from "./write_file.js";
test("writeFile writes and appends generated bytes", async () => {
    await withTestRoot(async (root) => {
        const file = join(root, "file");
        await writeFile(file, new Uint8Array([1, 2]));
        await writeFile(file, new Uint8Array([3]), { append: true });
        deepStrictEqual(await readFile(file), new Uint8Array([1, 2, 3]));
        await rejects(writeFile(join(root, "missing", "file"), new Uint8Array(), { create: false }));
    });
});
test("writeFileSync writes generated bytes", () => {
    withTestRootSync((root) => {
        const file = join(root, "file");
        writeFileSync(file, new Uint8Array([1, 2, 3]));
        deepStrictEqual(readFileSync(file), new Uint8Array([1, 2, 3]));
        throws(() => writeFileSync(join(root, "missing", "file"), new Uint8Array(), { create: false }));
    });
});
test("writeFile honors create and createNew flags with URL paths", async () => {
    await withTestRoot(async (root) => {
        const file = join(root, "file");
        await writeFile(pathToFileURL(file), new Uint8Array([1]), { createNew: true });
        await rejects(writeFile(file, new Uint8Array([2]), { createNew: true }));
        await writeFile(file, new Uint8Array([3]), { create: false });
        deepStrictEqual(await readFile(file), new Uint8Array([3]));
    });
});
test("writeFileSync creates only when requested", () => {
    withTestRootSync((root) => {
        const file = join(root, "file");
        throws(() => writeFileSync(file, new Uint8Array(), { create: false }));
        writeFileSync(file, new Uint8Array([1]), { createNew: true });
        writeFileSync(file, new Uint8Array([2]), { append: false, create: false });
        deepStrictEqual(readFileSync(file), new Uint8Array([2]));
        throws(() => writeFileSync(file, new Uint8Array(), { createNew: true }));
    });
});
test("writeFile accepts streams and abort signals", async () => {
    await withTestRoot(async (root) => {
        const file = join(root, "file");
        const stream = new ReadableStream({
            start(controller) {
                controller.enqueue(new Uint8Array([1, 2]));
                controller.close();
            },
        });
        await writeFile(file, stream);
        deepStrictEqual(await readFile(file), new Uint8Array([1, 2]));
        const controller = new AbortController();
        controller.abort();
        await rejects(writeFile(join(root, "aborted"), new Uint8Array(), { signal: controller.signal }));
    });
});
test("writeFile applies generated file modes", { skip: isWindows }, async () => {
    await withTestRoot(async (root) => {
        const file = join(root, "file");
        await writeFile(file, new Uint8Array([1]), { mode: 0o600 });
        deepStrictEqual(await readFile(file), new Uint8Array([1]));
        if ((await stat(file)).mode != null) {
            deepStrictEqual((await stat(file)).mode & 0o777, 0o600);
        }
    });
});
test("writeFileSync applies generated file modes", { skip: isWindows }, () => {
    withTestRootSync((root) => {
        const file = join(root, "file");
        writeFileSync(file, new Uint8Array([1]), { mode: 0o600 });
        deepStrictEqual(readFileSync(file), new Uint8Array([1]));
        if (statSync(file).mode != null) {
            deepStrictEqual(statSync(file).mode & 0o777, 0o600);
        }
    });
});
test("writeFile accepts an active signal and exposes abort names and reasons", async () => {
    await withTestRoot(async (root) => {
        const file = join(root, "file");
        const active = new AbortController();
        await writeFile(file, new Uint8Array([1]), { signal: active.signal });
        deepStrictEqual(await readFile(file), new Uint8Array([1]));
        const aborted = new AbortController();
        queueMicrotask(() => aborted.abort());
        await rejects(writeFile(join(root, "aborted"), new Uint8Array([2]), { signal: aborted.signal }), (error) => {
            strictEqual(error.name, "AbortError");
            return true;
        });
        const reason = new Error("reason");
        const withReason = new AbortController();
        queueMicrotask(() => withReason.abort(reason));
        await rejects(writeFile(join(root, "reason"), new Uint8Array([3]), { signal: withReason.signal }), (error) => {
            strictEqual(error === reason || error.cause === reason, true);
            return true;
        });
        const primitiveReason = "cancelled";
        const primitive = new AbortController();
        queueMicrotask(() => primitive.abort(primitiveReason));
        await rejects(writeFile(join(root, "primitive-reason"), new Uint8Array([4]), { signal: primitive.signal }), (error) => {
            strictEqual(error === primitiveReason ||
                error.cause === primitiveReason, true);
            return true;
        });
    });
});
test("writeFile does not create a path when its signal is already aborted", async () => {
    await withTestRoot(async (root) => {
        const file = join(root, "aborted");
        const controller = new AbortController();
        controller.abort();
        await rejects(writeFile(file, new Uint8Array([1]), { signal: controller.signal }), (error) => {
            strictEqual(error.name, "AbortError");
            return true;
        });
        strictEqual(await exists(file), false);
    });
});
test("writeFileSync appends bytes and rejects missing parents with default creation", () => {
    withTestRootSync((root) => {
        const file = join(root, "file");
        writeFileSync(file, new Uint8Array([1]));
        writeFileSync(file, new Uint8Array([2]), { append: true });
        deepStrictEqual(readFileSync(file), new Uint8Array([1, 2]));
        throws(() => writeFileSync(join(root, "missing", "file"), new Uint8Array([3])));
    });
});
test("writeFileSync changes an existing generated file mode", { skip: isWindows }, () => {
    withTestRootSync((root) => {
        const file = join(root, "file");
        writeFileSync(file, new Uint8Array([1]), { mode: 0o600 });
        writeFileSync(file, new Uint8Array([2]), { mode: 0o777 });
        strictEqual(statSync(file).mode & 0o777, 0o777);
    });
});
