import { deepStrictEqual as equal } from "node:assert/strict";
import { test } from "node:test";
import * as strings from "./mod.js";
test("strings::mod exports the public API", () => {
    equal(Object.keys(strings).sort(), [
        "StringBuilder",
        "camelize",
        "capitalize",
        "dasherize",
        "endsWith",
        "endsWithFold",
        "equal",
        "equalFold",
        "indexOf",
        "indexOfFold",
        "inflect",
        "isEmpty",
        "isNull",
        "isNullOrEmpty",
        "isNullOrSpace",
        "isSpace",
        "isUndefined",
        "lastIndexOf",
        "lastIndexOfFold",
        "pascalize",
        "pluralize",
        "singularize",
        "split",
        "startsWith",
        "startsWithFold",
        "titleize",
        "toCharArray",
        "toString",
        "trim",
        "trimChar",
        "trimEnd",
        "trimEndChar",
        "trimEndSlice",
        "trimSlice",
        "trimStart",
        "trimStartChar",
        "trimStartSlice",
        "underscore",
    ]);
});
