import "./_dnt.test_polyfills.js";
import { deepStrictEqual, rejects, throws } from "node:assert/strict";
import { test } from "node:test";
import { join } from "node:path";
import { pathToFileURL } from "node:url";
import { copyFile, copyFileSync } from "./copy_file.js";
import { ensureDirSync } from "./ensure_dir.js";
import { readFile, readFileSync } from "./read_file.js";
import { withTestRoot, withTestRootSync } from "./_test_helpers.js";
import { writeFile, writeFileSync } from "./write_file.js";
test("copyFile copies generated bytes", async () => {
    await withTestRoot(async (root) => {
        const source = join(root, "source");
        const destination = join(root, "destination");
        await writeFile(source, new Uint8Array([1, 2, 3]));
        await copyFile(source, destination);
        deepStrictEqual(await readFile(destination), new Uint8Array([1, 2, 3]));
    });
});
test("copyFileSync copies generated bytes", () => {
    withTestRootSync((root) => {
        const source = join(root, "source");
        const destination = join(root, "destination");
        writeFileSync(source, new Uint8Array([1, 2, 3]));
        copyFileSync(source, destination);
        deepStrictEqual(readFileSync(destination), new Uint8Array([1, 2, 3]));
    });
});
test("copyFile replaces a destination and rejects invalid sources", async () => {
    await withTestRoot(async (root) => {
        const source = join(root, "source");
        const destination = join(root, "destination");
        await writeFile(source, new Uint8Array([1]));
        await writeFile(destination, new Uint8Array([2]));
        await copyFile(pathToFileURL(source), pathToFileURL(destination));
        deepStrictEqual(await readFile(destination), new Uint8Array([1]));
        await rejects(copyFile(join(root, "missing"), destination));
    });
});
test("copyFileSync rejects a directory destination", () => {
    withTestRootSync((root) => {
        const source = join(root, "source");
        const directory = join(root, "directory");
        writeFileSync(source, new Uint8Array([1]));
        ensureDirSync(directory);
        throws(() => copyFileSync(source, directory));
    });
});
test("copyFile rejects directory destinations and replaces generated files", async () => {
    await withTestRoot(async (root) => {
        const source = join(root, "source");
        const destination = join(root, "destination");
        await writeFile(source, new Uint8Array([1]));
        await ensureDirSync(join(root, "directory"));
        await rejects(copyFile(source, join(root, "directory")));
        await writeFile(destination, new Uint8Array([2]));
        await copyFile(source, destination);
        deepStrictEqual(await readFile(destination), new Uint8Array([1]));
    });
});
test("copyFileSync replaces generated files and accepts new destinations", () => {
    withTestRootSync((root) => {
        const source = join(root, "source");
        const destination = join(root, "destination");
        writeFileSync(source, new Uint8Array([1]));
        writeFileSync(destination, new Uint8Array([2]));
        copyFileSync(source, destination);
        deepStrictEqual(readFileSync(destination), new Uint8Array([1]));
    });
});
test("copyFileSync creates a nonexistent generated destination", () => {
    withTestRootSync((root) => {
        const source = join(root, "source");
        const destination = join(root, "new-destination");
        writeFileSync(source, new Uint8Array([4, 5, 6]));
        copyFileSync(source, destination);
        deepStrictEqual(readFileSync(destination), new Uint8Array([4, 5, 6]));
    });
});
