import "./_dnt.test_polyfills.js";
import { deepStrictEqual, rejects, strictEqual, throws } from "node:assert/strict";
import { test } from "node:test";
import { join } from "node:path";
import { pathToFileURL } from "node:url";
import { readFile, readFileSync } from "./read_file.js";
import { withTestRoot, withTestRootSync } from "./_test_helpers.js";
import { writeFile, writeFileSync } from "./write_file.js";
test("readFile reads generated bytes and rejects missing files", async () => {
    await withTestRoot(async (root) => {
        const file = join(root, "file");
        await writeFile(file, new Uint8Array([0, 1, 255]));
        deepStrictEqual(await readFile(file), new Uint8Array([0, 1, 255]));
        await rejects(readFile(join(root, "missing")));
    });
});
test("readFileSync reads generated bytes and throws for missing files", () => {
    withTestRootSync((root) => {
        const file = join(root, "file");
        writeFileSync(file, new Uint8Array([0, 1, 255]));
        deepStrictEqual(readFileSync(file), new Uint8Array([0, 1, 255]));
        throws(() => readFileSync(join(root, "missing")));
    });
});
test("readFile accepts URLs and rejects directories", async () => {
    await withTestRoot(async (root) => {
        const file = join(root, "file");
        await writeFile(file, new Uint8Array([7]));
        deepStrictEqual(await readFile(pathToFileURL(file)), new Uint8Array([7]));
        await rejects(readFile(root));
    });
});
test("readFileSync rejects directories", () => {
    withTestRootSync((root) => throws(() => readFileSync(root)));
});
test("readFile honors an already-aborted signal", async () => {
    await withTestRoot(async (root) => {
        const file = join(root, "file");
        const controller = new AbortController();
        await writeFile(file, new Uint8Array([1]));
        controller.abort("cancelled");
        await rejects(readFile(file, { signal: controller.signal }));
    });
});
test("readFile can repeatedly read generated data and retains queued abort reasons", async () => {
    await withTestRoot(async (root) => {
        const file = join(root, "file");
        await writeFile(file, new Uint8Array([1, 2]));
        deepStrictEqual(await readFile(file), new Uint8Array([1, 2]));
        deepStrictEqual(await readFile(file), new Uint8Array([1, 2]));
        const controller = new AbortController();
        const reason = new Error("reason");
        queueMicrotask(() => controller.abort(reason));
        await rejects(readFile(file, { signal: controller.signal }), (error) => {
            strictEqual(error === reason || error.cause === reason, true);
            return true;
        });
        const primitiveReason = "cancelled";
        const primitive = new AbortController();
        queueMicrotask(() => primitive.abort(primitiveReason));
        await rejects(readFile(file, { signal: primitive.signal }), (error) => {
            strictEqual(error === primitiveReason ||
                error.cause === primitiveReason, true);
            return true;
        });
    });
});
test("readFile names a reasonless queued abort", async () => {
    await withTestRoot(async (root) => {
        const file = join(root, "file");
        const controller = new AbortController();
        await writeFile(file, new Uint8Array([1]));
        queueMicrotask(() => controller.abort());
        await rejects(readFile(file, { signal: controller.signal }), (error) => {
            strictEqual(error.name, "AbortError");
            return true;
        });
    });
});
test("readFileSync can repeatedly read generated data", () => {
    withTestRootSync((root) => {
        const file = join(root, "file");
        writeFileSync(file, new Uint8Array([1, 2]));
        deepStrictEqual(readFileSync(file), new Uint8Array([1, 2]));
        deepStrictEqual(readFileSync(file), new Uint8Array([1, 2]));
    });
});
